<?php

use Illuminate\Database\Seeder;
use App\Devis;

class DevisTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                //orchidectomie bilaterale
                // 'consultation_id' => '1',
                
                
                'nom'  => 'ORCHIDECTOMIE BILATERALE',
                'qte1' => '01',
                'qte2' => '100',
                'qte3'  => '50',
                'qte4' => '75',
                'qte5' => 'FF',
                'qte6' => '',
                'qte7' => '',
                'total1' => '566 000',
                'qte6' => '01',
                'qte7' => '01',
                'qte8' => '01',
                'prix_u' => '15 000',
                'prix_u1' => '1 500',
                'prix_u2' => '1500',
                'prix_u3' => '1500',
                'prix_u4' => '213 500',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => '10 000',

                'montant' => '15 000',
                'montant1' => '150 000',
                'montant2' => '75 000',
                'montant3' => '112 500',
                'montant4' => '213 500',
                
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'total2' => '49 000',
                'total3' => '615 000',

                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES + MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'SIX CENT QUINZE MILLE FRANCS CFA',

            ],

            [ //COELIOSCOPIE GYNECOLOGIQUE
                //'consultation_id' => '2',
                
                
                'nom'  => 'COELIOSCOPIE GYNECOLOGIQUE',
                'qte1' => '01',
                'qte2' => '80',
                'qte3'  => '40',
                'qte4' => '60',
                'qte5' => 'FF',
                'qte6' => '01',
                'qte7' => '01',
                'qte8' => '01',
                'prix_u' => '15 000',
                'prix_u1' => '1 500',
                'prix_u2' => '1500',
                'prix_u3' => '1500',
                'prix_u4' => '231 000',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => '10 000',

                'montant' => '15 000',
                'montant1' => '120 000',
                'montant2' => '60 000',
                'montant3' => '90 000',
                'montant4' => '231 000',
                'montant5' => '516 000',
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'montant9' => '49 000',
                'total3' => '550 000',

                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'CINQ CENT QUINZE MILLE FRANCS CFA',

            ],

            [ //PYELOTOMIE LAPAROSCOPIQUE + JJ
                // 'consultation_id' => '3',
                
                
                'nom'  => 'PYELOTOMIE LAPAROSCOPIQUE + JJ',
                'qte1' => '01',
                'qte2' => '120',
                'qte3'  => '60',
                'qte4' => '90',
                'qte5' => 'FF',
                'qte6' => '03',
                'qte7' => '03',
                'qte8' => '03',
                'prix_u' => '15 000',
                'prix_u1' => '1 500',
                'prix_u2' => '1500',
                'prix_u3' => '1500',
                'prix_u4' => '848 000',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => '10 000',

                'montant' => '15 000',
                'montant1' => '300 000',
                'montant2' => '150 000',
                'montant3' => '225 000',
                'montant4' => '678 000',
                'montant5' => '1 368000',
                'montant6' => '90 000',
                'montant7' => '27 000',
                'montant8' => '30 000',
                'montant9' => '147 000',
                'total3' => '1 515 000',

                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'UN MILLION CINQ CENT QUINZE MILLE FRANCS CFA',
            ],

            [ //POSTHECTOMIE SOUS ANESTHESIE GENERALE
                // 'consultation_id' => '4',
                
                
                'nom'  => 'POSTHECTOMIE SOUS ANESTHESIE GENERALE',
                'qte1' => '01',
                'qte2' => '30',
                'qte3'  => '15',
                'qte4' => '22.5',
                'qte5' => 'FF',
                'qte6' => '01',
                'qte8' => '01',
                'prix_u' => '15 000',
                'prix_u1' => '1 500',
                'prix_u2' => '1500',
                'prix_u3' => '1500',
                'prix_u4' => '114 750',
                'prix_u5' => '10 000',
                'prix_u6' => '9 000',
                'prix_u7' => '00',
                'prix_u8' => ' 000',
                'montant' => '15 000',
                'montant1' => '45 000',
                'montant2' => '22 500',
                'montant3' => '33 750',
                'montant4' => '114 750',
                'montant5' => '231 000',
                'montant6' => '10 000',
                'montant7' => '9 000',
                'montant8' => '19 000',
                'montant9' => '000',
                'total3' => '250 000',
                'montant11' => ' 000',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'DEUX CENT CINQUANTE MILLE FRANCS CFA',
            ],

            [ //HYSTEROSCOPIE RESECTION
                // 'consultation_id' => '5',
                
               
                'nom'  => 'HYSTEROSCOPIE RESECTION',
                'qte1' => '01',
                'qte2' => '50',
                'qte3'  => '40',
                'qte4' => '45',
                'qte5' => 'FF',
                'qte6' => '01',
                'qte7' => '01',
                'qte8' => '01',
                'prix_u' => '15 000',
                'prix_u1' => '1 500',
                'prix_u2' => '1500',
                'prix_u3' => '1500',
                'prix_u4' => '30 000',
                'prix_u5' => '9 000',
                'prix_u6' => '10 000',
                'prix_u7' => '00',

                'montant' => '15 000',
                'montant1' => '75 000',
                'montant2' => '60 000',
                'montant3' => '67 500',
                'montant4' => '166 000',
                'montant5' => '316 000',
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'montant9' => '49 000',
                'total3' => '365 000',

                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'TROIS CENT SOIXANTE CINQ MILLE FRANCS CFA',
            ],

            [
                //CURE DE VARICOCELE LAPAROSCOPIQUE
                
                
                'nom'  => 'CURE DE VARICOCELE LAPAROSCOPIQUE',
                'qte1' => '01',
                'qte2' => '120',
                'qte3'  => '60',
                'qte4' => '90',
                'qte5' => 'FF',
                'qte6' => '01',
                'qte7' => '01',
                'qte8' => '01',
                'qte9' => '',
                'qte10' => '',
                'qte11' => '',

                'prix_u' => '15 000',
                'prix_u1' => '1 500',
                'prix_u2' => '1500',
                'prix_u3' => '1500',
                'prix_u4' => '546 000',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => '10 000',
                'prix_u8' => ' 000',
                'montant' => '15 000',
                'montant1' => '180 000',
                'montant2' => '90 000',
                'montant3' => '135 000',
                'montant4' => '450 000',
                'montant5' => '870 000',
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'montant9' => '49 000',
                'montant10' => '',
                'total3' => '919 000',
                'total2' => '319 000',

                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => '',
                'elements6' => '',

                'elements7' => 'CHAMBRE',
                'elements8' => 'AMI-JOUR (750x12)',
                'elements9' => 'VISITE',
                'elements10' => '',
                'arreter' => 'NEUF CENT DIX NEUF MILLE FRANCS CFA',
            ],
            [
                //BIOPSIES PROSTATIQUES SOUS ECHOGUIDEES
                
                
                'nom'  => 'BIOPSIES PROSTATIQUES SOUS ECHOGUIDEES',
                'qte1' => '40',
                'qte2' => '20',
                'qte5' => 'FF',

                'prix_u' => '1 500',
                'prix_u1' => '1 500',
                'prix_u2' => '55 000',

                'montant' => '60 000',
                'montant1' => '30 000',
                'montant2' => '55 000',

                'total3' => '145 000',

                'elements' => 'KC',
                'elements1' => 'ANATOMO-PATHOLOGIE',

                'elements2' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',

                'arreter' => 'CENT QUARANTE CINQ MILLE FRANCS CFA',
            ],

            [
                //BIOPSIES PROSTATIQUES ECHO-GUIDEES SOUS SEDATION
                
                
                'nom'  => 'BIOPSIES PROSTATIQUES ECHO-GUIDEES SOUS SEDATION',
                'qte1' => '50',
                'qte2' => '30',
                'qte5' => 'FF',

                'prix_u' => '1 500',
                'prix_u1' => '1 500',
                'prix_u2' => '80 000',
                'prix_u3' => '00',
                'prix_u4' => ' 000',
                'prix_u5' => '000',
                'prix_u6' => '000',
                'prix_u7' => ' 000',
                'prix_u8' => ' 000',
                'montant' => '75 000',
                'montant1' => '45 000',
                'montant2' => '80 000',
                'total3' => '200 000',
                'elements' => 'KC',
                'elements1' => 'KA',
                'elements2' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',

                'arreter' => 'DEUX CENT MILLE FRANCS CFA',
            ],

            [
                //NLPC + NEPHROSTOMIE
                
                
                'nom'  => 'NLPC + NEPHROSTOMIE',
                'qte1' => '01',
                'qte2' => '160',
                'qte3'  => '50',
                'qte4' => '120',
                'qte5' => '140',
                'qte6' => 'FF',
                'qte7' => '03',
                'qte8' => '03',
                'qte9' => '03',
                'prix_u' => '1 5000',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '1 500',
                'prix_u4' => ' 1 500',
                'prix_u5' => '1 500',
                'prix_u6' => '837',
                'prix_u7' => ' 30 000',
                'prix_u8' => ' 9 000',
                'montant' => '15 000',
                'montant1' => '240 000',
                'montant2' => '75 000',
                'montant3' => '180 000',
                'montant4' => '210 000',
                'montant5' => '837 000',
                'montant6' => '1557 000',
                'montant7' => '90 000',
                'montant8' => '27 000',
                'montant9' => '30 000',
                'total3' => '147000',
                'montant11' => '1 704 000',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'UN MILLION SEPT CENT QUATRE MILLE FRANCS FCFA',
            ],

            [
                //PROSTATECTOMIE RADICALE TOTALE PAR COELIOSCOPIE
                
                
                'nom'  => 'PROSTATECTOMIE RADICALE TOTALE PAR COELIOSCOPIE',
                'qte1' => '01',
                'qte2' => '250',
                'qte3'  => '50',
                'qte4' => '266,6',
                'qte5' => '283,33',
                'qte6' => 'FF',
                'qte7' => '04',
                'qte8' => '04',
                'qte9' => '04',
                'prix_u' => '1 5000',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '1 500',
                'prix_u4' => ' 1 500',
                'prix_u5' => '1014 000',
                'prix_u6' => '30 000',
                'prix_u7' => ' 9 000',
                'prix_u8' => ' 10 000',
                'montant' => '15 000',
                'montant1' => '375 000',
                'montant2' => '75 000',
                'montant3' => '400 000',
                'montant4' => '425 000',
                'montant5' => '1014 000',
                'montant6' => '2 314 000',
                'montant7' => '120 000',
                'montant8' => '36 000',
                'montant9' => '40 000',
                'total3' => '2 500 000',
                'montant11' => '196 000',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KCC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'elements8' => 'K',
                'arreter' => 'DEUX MILLIONS CINQ CENT MILLE FRANS CFA',
            ],



            [
                //MISE EN PLACE SONDE DOUBLE J PAR VOIE ENDOSCOPIQUE
                
                
                'nom'  => 'MISE EN PLACE SONDE DOUBLE J PAR VOIE ENDOSCOPIQUE',
                'qte1' => '01',
                'qte2' => '80',
                'qte3'  => '00',
                'qte4' => '40',
                'qte5' => '60',
                'qte6' => 'FF',
                'qte7' => '01',
                'qte8' => '01',
                'qte9' => '01',
                'prix_u' => '1 5000',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '1 500',
                'prix_u4' => ' 259 250',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => ' 10 000',

                'montant' => '15 000',
                'montant1' => '120 000',
                'montant2' => '92 000',
                'montant3' => '64 000',
                'montant4' => '200 000',
                'montant5' => '566 000',
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'montant9' => '49 000',
                'total3' => '615 000',
                'montant11' => '75 000',

                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'elements8' => 'AMPLIFICATEUR DE BRILLANCE',
                'arreter' => 'SIX CENT QUINZE MILLE FRANCS CFA',
            ],

            [
                //URETEROSCOPIE SOUPLE LASER +MISE EN PLACE SONDE JJ
                
                
                'nom'  => 'URETEROSCOPIE SOUPLE LASER +MISE EN PLACE SONDE JJ',
                'qte1' => '01',
                'qte2' => '160',
                'qte3'  => '50',
                'qte4' => '120',
                'qte5' => '140',
                'qte6' => 'FF',
                'qte7' => '02',
                'qte8' => '02',
                'qte9' => '02',
                'prix_u' => '1 5000',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '1 500',
                'prix_u4' => ' 1 500',
                'prix_u5' => '837',
                'prix_u6' => '30 000',
                'prix_u7' => ' 9 000',
                'prix_u8' => ' 10 000',
                'montant' => '15 000',
                'montant1' => '240 000',
                'montant2' => '75 000',
                'montant3' => '180 000',
                'montant4' => '210 000',
                'montant5' => '837 000',
                'montant6' => '1 557 000',
                'montant7' => '60 000',
                'montant8' => '18 000',
                'montant9' => '20 000',
                'total3' => '1 655 000',
                'montant11' => '98 000',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'elements8' => 'K (AMPLIFICATEUR DE BRILLANCE)',
                'arreter' => 'UN MILLION SIX CENT CINQUANTE ET CINQ MILLE FCFA',
            ],


            [
                //CATHETER SUS-PUBIEN
                
                
                'nom'  => 'CATHETER SUS-PUBIEN SOUS LOCALE',
                'qte1' => '20',
                'qte2' => '10',
                'qte3'  => '15',
                'qte6' => 'FF',
                'qte5' => '00',
                'qte6' => '00',
                'qte7' => '00',
                'qte8' => '00',
                'prix_u' => '1 500',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '37 500',
                'prix_u4' => ' 00',
                'prix_u5' => '00',
                'prix_u6' => '00',
                'prix_u7' => '00',
                'prix_u8' => '00',
                'montant' => '30 000',
                'montant1' => '15 000',
                'montant2' => '22 500',
                'montant3' => '37 500',
                'montant4' => '105 000',
                'montant5' => '00',
                'montant6' => '00',
                'montant7' => '00',
                'montant8' => '00',
                'montant9' => '00',
                'total3' => '',
                'montant11' => '00',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'CENT CINQ MILLLE FRANCS CFA',
            ],
            [
                //CYSTOCOPIE DIAGNOSTIQUE + ECHOGRAPHIE
                
                
                'nom'  => 'ECHOGRAPHIE + CYSTOCOPIE DIAGNOSTIQUE  ',
                'qte1' => '27',
                'qte2' => '13',
                'qte3'  => '01',
                'qte4' => '00',
                'qte5' => '00',
                'qte6' => 'FF',
                'qte7' => '00',
                'qte8' => '00',
                'prix_u' => '1 500',
                'prix_u1' => '1 500',
                'prix_u2' => '25 000',
                'prix_u3' => '20 000',
                'prix_u4' => ' 00',
                'prix_u5' => '00',
                'prix_u6' => '00',
                'prix_u7' => '00',
                'prix_u8' => '00',
                'montant' => '40 500',
                'montant1' => '19 500',
                'montant2' => '25 000',
                'montant3' => '85 000',
                'montant4' => '20 000',
                'montant5' => '20 000',
                'montant6' => '00',
                'montant7' => '00',
                'montant8' => '00',
                'montant9' => '00',
                'total3' => '105 000',
                'montant11' => '00',
                'elements' => 'KC',
                'elements1' => 'KA',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ',
                'elements5' => '',
                'elements6' => '',
                'elements7' => '',
                'arreter' => 'CENT CINQ MILLE FRANCS CFA',
            ],

            [
                //DEBITMETRIE + CYSTOCOPIE
                
                
                'nom'  => ' DEBITMETRIE + CYSTOCOPIE',
                'qte1' => '27',
                'qte2' => '13',
                'qte3'  => '01',
                'qte4' => 'FF',
                'qte5' => '00',
                'qte6' => '00',
                'qte7' => '00',
                'qte8' => '00',
                'prix_u' => '1 500',
                'prix_u1' => '1 500',
                'prix_u2' => '25 000',
                'prix_u3' => '15 000',
                'prix_u4' => ' 00',
                'prix_u5' => '00',
                'prix_u6' => '00',
                'prix_u7' => '00',
                'prix_u8' => '00',
                'montant' => '40 500',
                'montant1' => '19 500',
                'montant2' => '25 000',
                'montant3' => '15 000',
                'montant4' => '00',
                'montant5' => '00',
                'montant6' => '00',
                'montant7' => '00',
                'montant8' => '00',
                'montant9' => '00',
                'total3' => '100 000',
                'montant11' => '00',
                'elements' => 'KC',
                'elements1' => 'KA',
                'elements2' => '',
                'elements3' => '',
                'elements4' => 'MATERIELS OPERATOIRES ',
                'elements5' => '',
                'elements6' => '',
                'elements7' => '',
                'arreter' => 'CENT MILLE FRANCS CFA',
            ],

            [
                //CYSTOCOPIE SOUS LOCAL
                
                
                'nom'  => 'CYSTOCOPIE SOUS LOCALE',
                'qte1' => '27',
                'qte2' => '13',
                'qte3'  => '00',
                'qte4' => 'FF',
                'qte5' => '00',
                'qte6' => '00',
                'qte7' => '00',
                'qte8' => '00',
                'prix_u' => '1 500',
                'prix_u1' => '1 500',
                'prix_u2' => '25 000',
                'prix_u3' => '00',
                'prix_u4' => ' 00',
                'prix_u5' => '00',
                'prix_u6' => '00',
                'prix_u7' => '00',
                'prix_u8' => '00',
                'montant' => '40 500',
                'montant1' => '19 500',
                'montant2' => '25 000',
                'montant3' => '00',
                'montant4' => '00',
                'montant5' => '00',
                'montant6' => '00',
                'montant7' => '00',
                'montant8' => '00',
                'montant9' => '00',
                'total3' => '85 000',
                'montant11' => '00',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ',
                'elements5' => '',
                'elements6' => '',
                'elements7' => '',
                'arreter' => 'QUATRE VINGT CINQ MILLE FRANCS CFA',
            ],
            [
                //ABLATION SONDE DOUBLE J
                
                
                'nom'  => 'ABLATION SONDE DOUBLE J',
                'qte1' => '27',
                'qte2' => '13',
                'qte3'  => '00',
                'qte4' => 'FF',
                'qte5' => '00',
                'qte6' => '00',
                'qte7' => '00',
                'qte8' => '00',
                'prix_u' => '1 500',
                'prix_u1' => '1 500',
                'prix_u2' => '25 000',
                'prix_u3' => '00',
                'prix_u4' => ' 00',
                'prix_u5' => '00',
                'prix_u6' => '00',
                'prix_u7' => '00',
                'prix_u8' => '00',
                'montant' => '40 500',
                'montant1' => '19 500',
                'montant2' => '25 000',
                'montant3' => '00',
                'montant4' => '00',
                'montant5' => '00',
                'montant6' => '00',
                'montant7' => '00',
                'montant8' => '00',
                'montant9' => '00',
                'total3' => '85 000',
                'montant11' => '00',
                'elements' => 'KC',
                'elements1' => 'KB',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'QUATRE VINGT CINQ MILLE FRANCS CFA',
            ],


            [
                //CYSTOCOPIE DIAGNOSTIQUE + ECHOGRAPHIE
                
                
                'nom'  => 'CYSTOCOPIE DIAGNOSTIQUE + ECHOGRAPHIE',
                'qte1' => '27',
                'qte2' => '13',
                'qte3'  => '01',
                'qte4' => 'FF',
                'qte5' => '00',
                'qte6' => '00',
                'qte7' => '00',
                'qte8' => '00',
                'prix_u' => '1 500',
                'prix_u1' => '1 500',
                'prix_u2' => '25 000',
                'prix_u3' => '20 000',
                'prix_u4' => ' 00',
                'prix_u5' => '00',
                'prix_u6' => '00',
                'prix_u7' => '00',
                'prix_u8' => '00',
                'montant' => '40 500',
                'montant1' => '19 500',
                'montant2' => '25 000',
                'montant3' => '85 000',
                'montant4' => '20 000',
                'montant5' => '20 000',
                'montant6' => '00',
                'montant7' => '00',
                'montant8' => '00',
                'montant9' => '00',
                'total3' => '105 000',
                'montant11' => '00',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ',
                'elements5' => '',
                'elements6' => '',
                'elements7' => '',
                'arreter' => 'CENT CINQ MILLE FRANCS CFA',
            ],

            [
                //CACHETER SUS PUBIEN SOUS LOCALE
                
                
                'nom'  => 'CACHETER SUS PUBIEN SOUS LOCALE',
                'qte1' => '20',
                'qte2' => '10',
                'qte3'  => '15',
                'qte4' => '00',
                'qte5' => '00',
                'qte6' => '00',
                'qte7' => '00',
                'qte8' => '00',
                'prix_u' => '1 500',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '37 500',
                'prix_u4' => ' 00',
                'prix_u5' => '00',
                'prix_u6' => '00',
                'prix_u7' => '00',
                'prix_u8' => '00',
                'montant' => '30 000',
                'montant1' => '15 000',
                'montant2' => '22 500',
                'montant3' => '37 500',
                'montant4' => '00',
                'montant5' => '00',
                'montant6' => '00',
                'montant7' => '00',
                'montant8' => '00',
                'montant9' => '00',
                'total3' => '105 000',
                'montant11' => '00',
                'elements' => 'KC',
                'elements1' => 'KA',
                'elements2' => '',
                'elements3' => '',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => '',
                'elements6' => '',
                'elements7' => '',
                'arreter' => 'CENT CINQ MILLLE FRANCS CFA',
            ],


            [
                //URETEROSCOPIE RETROGRADE SEMI-RIGIDE
                
                
                'nom'  => 'URETEROSCOPIE RETROGRADE SEMI-RIGIDE',
                'qte1' => '01',
                'qte2' => '80',
                'qte3'  => '00',
                'qte4' => '40',
                'qte5' => '60',
                'qte6' => '01',
                'qte7' => '01',
                'qte8' => '01',
                'prix_u' => '1 5000',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '1 500',
                'prix_u4' => ' 259 250',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => ' 10 000',
                'prix_u8' => ' 00',
                'montant' => '15 000',
                'montant1' => '120 000',
                'montant2' => '92 000',
                'montant3' => '64 000',
                'montant4' => '200 000',
                'montant5' => '566 000',
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'montant9' => '49 000',
                'total3' => '1545 000',
                'montant11' => '00',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'UN MILLION CINQ CENT QUARENTE CINQ MILLE FRANCS CFA',
            ],

            [
                //PROSTATECTOMIE RADICALE TOTALE PAR COELIOSCOPIE
                
                
                'nom'  => 'PROSTATECTOMIE RADICALE TOTALE PAR COELIOSCOPIE			',
                'qte1' => '01',
                'qte2' => '80',
                'qte3'  => '00',
                'qte4' => '40',
                'qte5' => '60',
                'qte6' => '01',
                'qte7' => '01',
                'qte8' => '01',
                'prix_u' => '1 5000',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '1 500',
                'prix_u4' => ' 259 250',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => ' 10 000',
                'prix_u8' => ' 00',
                'montant' => '15 000',
                'montant1' => '120 000',
                'montant2' => '92 000',
                'montant3' => '64 000',
                'montant4' => '200 000',
                'montant5' => '566 000',
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'montant9' => '49 000',
                'total3' => '2500 000',
                'montant11' => '00',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'DEUX MILLIONS CINQ CENT MILLE FRANCS CFA',
            ],


            [
                //NEPHROSTOMIE UNILATERALE
                
                
                'nom'  => 'NEPHROSTOMIE UNILATERALE',
                'qte1' => '01',
                'qte2' => '80',
                'qte3'  => '00',
                'qte4' => '40',
                'qte5' => '60',
                'qte6' => '01',
                'qte7' => '01',
                'qte8' => '01',
                'prix_u' => '1 5000',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '1 500',
                'prix_u4' => ' 259 250',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => ' 10 000',
                'prix_u8' => ' 00',
                'montant' => '15 000',
                'montant1' => '120 000',
                'montant2' => '92 000',
                'montant3' => '64 000',
                'montant4' => '200 000',
                'montant5' => '566 000',
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'montant9' => '49 000',
                'total3' => '615 000',
                'montant11' => '00',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'SIX CENT QUINZE MILLE FRANCS CFA',
            ],

            [
                //SONDE DOUBLE J
                
                
                'nom'  => 'SONDE DOUBLE J',
                'qte1' => '01',
                'qte2' => '80',
                'qte3'  => '00',
                'qte4' => '40',
                'qte5' => '60',
                'qte6' => '01',
                'qte7' => '01',
                'qte8' => '01',
                'prix_u' => '1 5000',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '1 500',
                'prix_u4' => ' 259 250',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => ' 10 000',
                'prix_u8' => ' 00',
                'montant' => '15 000',
                'montant1' => '120 000',
                'montant2' => '92 000',
                'montant3' => '64 000',
                'montant4' => '200 000',
                'montant5' => '566 000',
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'montant9' => '49 000',
                'total3' => '615 000',
                'montant11' => '00',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'SIX CENT QUINZE MILLE FRANCS CFA',
            ],

            [
                //URETEROSCOPIE SOUPLE LASER ET SONDE JJ
                
                
                'nom'  => 'URETEROSCOPIE SOUPLE LASER ET SONDE JJ',
                'qte1' => '01',
                'qte2' => '80',
                'qte3'  => '00',
                'qte4' => '40',
                'qte5' => '60',
                'qte6' => '01',
                'qte7' => '01',
                'qte8' => '01',
                'prix_u' => '1 5000',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '1 500',
                'prix_u4' => ' 259 250',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => ' 10 000',
                'prix_u8' => ' 00',
                'montant' => '15 000',
                'montant1' => '120 000',
                'montant2' => '92 000',
                'montant3' => '64 000',
                'montant4' => '200 000',
                'montant5' => '566 000',
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'montant9' => '49 000',
                'total3' => '1 655 000',
                'montant11' => '00',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'UN MILLION SIX CENT CINQUANTE CINQ MILLE FRANCS CFA',
            ],


            [
                //URETROTOMIE INTERNE ENDOSCOPIQUE
                
                
                'nom'  => 'URETROTOMIE INTERNE ENDOSCOPIQUE',
                'qte1' => '01',
                'qte2' => '80',
                'qte3'  => '00',
                'qte4' => '40',
                'qte5' => '60',
                'qte6' => '01',
                'qte7' => '01',
                'qte8' => '01',
                'prix_u' => '1 5000',
                'prix_u1' => '1 500',
                'prix_u2' => '1 500',
                'prix_u3' => '1 500',
                'prix_u4' => ' 259 250',
                'prix_u5' => '30 000',
                'prix_u6' => '9 000',
                'prix_u7' => ' 10 000',
                'prix_u8' => ' 00',
                'montant' => '15 000',
                'montant1' => '120 000',
                'montant2' => '92 000',
                'montant3' => '64 000',
                'montant4' => '200 000',
                'montant5' => '566 000',
                'montant6' => '30 000',
                'montant7' => '9 000',
                'montant8' => '10 000',
                'montant9' => '49 000',
                'total3' => '1015 000',
                'montant11' => '00',
                'elements' => 'CS ANESTHESIE',
                'elements1' => 'KC',
                'elements2' => 'KA',
                'elements3' => 'KB',
                'elements4' => 'MATERIELS OPERATOIRES ET MEDICAMENTS',
                'elements5' => 'CHAMBRE',
                'elements6' => 'AMI-JOUR (750x12)',
                'elements7' => 'VISITE',
                'arreter' => 'UN MILLION QUINZE MILLE FRANCS CFA',
            ],

        ];
        foreach ($data as $key => $value) {

            Devis::create($value);
        }

    }
}
