<?php

namespace App\Http\Controllers;

use App\Devisd;
use App\Consultation;
use App\Patient;
use\App\Devis;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;

class DevisdController extends Controller
{
    public function index(Consultation $consultation)
    {
       
        $devisd = Devisd::orderBy('id', 'asc')->paginate(100);

        return view('admin.devisd.index', compact('devisd'));
    }


    public function store(Request $request)
    {

        $this->authorize('create', Patient::class);


        $request->validate([

            'nom'=> ['', 'unique:devis'],
            'prix1'=> '',
            'prix2'=> '',
            'prix3'=> '',
            'prix4'=> '',
            'prix5'=> '',
            'prix6'=> '',
            'prix7'=> '',
            'prix8'=> '',
            'prix9'=> '',
            'prix10'=> '',
            'prix11'=> '',
            'prix12'=> '',
            'prix13'=> '',
            'prix14'=> '',
            'prix15'=> '',
            'prix16'=> '',
            'prix17'=> '',
            'prix18'=> '',
            'prix19'=> '',
            'prix20'=> '',
            'prix21'=> '',
            'prix22'=> '',
            'prix23'=> '',
            'prix24'=> '',
            'prix25'=> '',
            'prix26'=> '',
            'prix27'=> '',
            'prix28'=> '',
            'prix29'=> '',
            'prix30'=> '',
            'prix31'=> '',
            'prix32'=> '',
            'prix33'=> '',
            'prix34'=> '',
            'prix35'=> '',
            'prix36'=> '',
            'prix37'=> '',
            'prix38'=> '',
            'prix39'=> '',
            'prix40'=> '',
            'prix41'=> '',
            'prix42'=> '',
            'prix43'=> '',
            'prix44'=> '',
            'prix45'=> '',
            'prix46'=> '',
            'prix47'=> '',
            'prix48'=> '',
            'prix49'=> '',
            'prix50'=> '',
            'prix51'=> '',
            'prix52'=> '',
            'prix53'=> '',
            'prix54'=> '',
            'prix55'=> '',
            'prix56'=> '',
            'prix57'=> '',
            'prix58'=> '',
            'prix59'=> '',
            'prix60'=> '',
            'prix61'=> '',
            'prix62'=> '',
            'prix63'=> '',
            'prix64'=> '',
            'prix65'=> '',
            'prix66'=> '',
            'prix67'=> '',
            'prix68'=> '',
            'prix69'=> '',
            'prix70'=> '',
            'prix71'=> '',
            'prix72'=> '',
            'prix73'=> '',
            'prix74'=> '',
            'prix75'=> '',
            'prix76'=> '',
            'prix77'=> '',
            'prix78'=> '',
            'prix79'=> '',
            'prix80'=> '',
            'prix81'=> '',
            'prix82'=> '',
            'prix83'=> '',
            'prix84'=> '',
            'prix85'=> '',
            'prix86'=> '',
            'prix87'=> '',
            'prix88'=> '',
            'prix89'=> '',
            'prix90'=> '',
            'prix91'=> '',
            'prix92'=> '',
            'prix93'=> '',
            'prix94'=> '',
            'prix95'=> '',
            'prix96'=> '',
            'prix97'=> '',
            'prix98'=> '',
            'prix99'=> '',
            'prix100'=> '',
            'prix101'=> '',
            'prix102'=> '',
            'prix103'=> '',
            'prix104'=> '',
            'prix105'=> '',
            'prix106'=> '',
            'prix107'=> '',
            'prix108'=> '',
            'prix109'=> '',
            'prix110'=> '',
            'prix111'=> '',
            'prix112'=> '',
            'prix113'=> '',
            'prix114'=> '',
            'prix115'=> '',
            'prix116'=> '',
            'prix117'=> '',
            'prix118'=> '',
            'prix119'=> '',
            'prix120'=> '',
            'prix121'=> '',
            'prix122'=> '',
            'prix123'=> '',
            'prix124'=> '',
            'prix125'=> '',
            'prix126'=> '',
            'prix127'=> '',
            'prix128'=> '',
            'prix129'=> '',
            'prix130'=> '',
            'prix131'=> '',
            'prix132'=> '',
            'prix133'=> '',
            'prix134'=> '',
            'prix135'=> '',
            'prix136'=> '',
            'prix137'=> '',
            'prix138'=> '',
            'prix139'=> '',
            'prix140'=> '',
            'prix141'=> '',
            'prix142'=> '',
            'prix143'=> '',
            'prix144'=> '',
            'prix145'=> '',
            'prix146'=> '',
            'prix147'=> '',
            'prix148'=> '',
            'prix149'=> '',
            'prix150'=> '',

            'souselements1'=> '',
            'souselements2'=> '',
            'souselements3'=> '',
            'souselements4'=> '',
            'souselements5'=> '',
            'souselements6'=> '',
            'souselements7'=> '',
            'souselements8'=> '',
            'souselements9'=> '',
            'souselements10'=> '',
            'souselements11'=> '',
            'souselements12'=> '',
            'souselements13'=> '',
            'souselements14'=> '',
            'souselements15'=> '',
            'souselements16'=> '',
            'souselements17'=> '',
            'souselements18'=> '',
            'souselements19'=> '',
            'souselements20'=> '',
            'souselements21'=> '',
            'souselements22'=> '',
            'souselements23'=> '',
            'souselements24'=> '',
            'souselements25'=> '',
            'souselements26'=> '',
            'souselements27'=> '',
            'souselements28'=> '',
            'souselements29'=> '',
            'souselements30'=> '',
            'souselements31'=> '',
            'souselements32'=> '',
            'souselements33'=> '',
            'souselements34'=> '',
            'souselements35'=> '',
            'souselements36'=> '',
            'souselements37'=> '',
            'souselements38'=> '',
            'souselements39'=> '',
            'souselements40'=> '',
            'souselements41'=> '',
            'souselements42'=> '',
            'souselements43'=> '',
            'souselements44'=> '',
            'souselements45'=> '',
            'souselements46'=> '',
            'souselements47'=> '',
            'souselements48'=> '',
            'souselements49'=> '',
            'souselements50'=> '',
            'souselements51'=> '',
            'souselements52'=> '',
            'souselements53'=> '',
            'souselements54'=> '',
            'souselements55'=> '',
            'souselements56'=> '',
            'souselements57'=> '',
            'souselements58'=> '',
            'souselements59'=> '',
            'souselements60'=> '',
            'souselements61'=> '',
            'souselements62'=> '',
            'souselements63'=> '',
            'souselements64'=> '',
            'souselements65'=> '',
            'souselements66'=> '',
            'souselements67'=> '',
            'souselements68'=> '',
            'souselements69'=> '',
            'souselements70'=> '',
            'souselements71'=> '',
            'souselements72'=> '',
            'souselements73'=> '',
            'souselements74'=> '',
            'souselements75'=> '',
            'souselements76'=> '',
            'souselements77'=> '',
            'souselements78'=> '',
            'souselements79'=> '',
            'souselements80'=> '',
            'souselements81'=> '',
            'souselements82'=> '',
            'souselements83'=> '',
            'souselements84'=> '',
            'souselements85'=> '',
            'souselements86'=> '',
            'souselements87'=> '',
            'souselements88'=> '',
            'souselements89'=> '',
            'souselements90'=> '',
            'souselements91'=> '',
            'souselements92'=> '',
            'souselements93'=> '',
            'souselements94'=> '',
            'souselements95'=> '',
            'souselements96'=> '',
            'souselements97'=> '',
            'souselements98'=> '',
            'souselements99'=> '',
            'souselements100'=> '',
            'souselements101'=> '',
            'souselements102'=> '',
            'souselements103'=> '',
            'souselements104'=> '',
            'souselements105'=> '',
            'souselements106'=> '',
            'souselements107'=> '',
            'souselements108'=> '',
            'souselements109'=> '',
            'souselements110'=> '',
            'souselements111'=> '',
            'souselements112'=> '',
            'souselements113'=> '',
            'souselements114'=> '',
            'souselements115'=> '',
            'souselements116'=> '',
            'souselements117'=> '',
            'souselements118'=> '',
            'souselements119'=> '',
            'souselements120'=> '',
            'souselements121'=> '',
            'souselements122'=> '',
            'souselements123'=> '',
            'souselements124'=> '',
            'souselements125'=> '',
            'souselements126'=> '',
            'souselements127'=> '',
            'souselements128'=> '',
            'souselements129'=> '',
            'souselements130'=> '',
            'souselements131'=> '',
            'souselements132'=> '',
            'souselements133'=> '',
            'souselements134'=> '',
            'souselements135'=> '',
            'souselements136'=> '',
            'souselements137'=> '',
            'souselements138'=> '',
            'souselements139'=> '',
            'souselements140'=> '',
            'souselements141'=> '',
            'souselements142'=> '',
            'souselements143'=> '',
            'souselements144'=> '',
            'souselements145'=> '',
            'souselements146'=> '',
            'souselements147'=> '',
            'souselements148'=> '',
            'souselements149'=> '',
            'souselements150'=> '',
            'devis_id'=> '',
            'elements1'=> '',
            'elements2'=> '',
            'elements3'=> '',
            'elements4'=> '',
            'elements5'=> '',
            'elements6'=> '',
            'elements7'=> '',
            'elements8'=> '',
            'elements9'=> '',
            'elements10'=> '',
            'elements11'=> '',
            'elements12'=> '',
            'elements13'=> '',
            'elements14'=> '',
            'elements15'=> '',
            'arreter'=> '',
            'total1'=> '',
            'total2'=> '',
            'total3'=> '',



        ]);
        $devisd = new Devisd();
       $devisd->souselements1 = $request->get('souselements1');
        $devisd->souselements2 = $request->get('souselements2');
        $devisd->souselements3 = $request->get('souselements3');
        $devisd->souselements4 = $request->get('souselements4');
        $devisd->souselements5 = $request->get('souselements5');
        $devisd->souselements6 = $request->get('souselements6');
        $devisd->souselements7 = $request->get('souselements7');
        $devisd->souselements8 = $request->get('souselements8');
        $devisd->souselements9 = $request->get('souselements9');
        $devisd->souselements10 = $request->get('souselements10');
        $devisd->souselements11 = $request->get('souselements11');
        $devisd->souselements12 = $request->get('souselements12');
        $devisd->souselements13 = $request->get('souselements13');
        $devisd->souselements14 = $request->get('souselements14');
        $devisd->souselements15 = $request->get('souselements15');
        $devisd->souselements16 = $request->get('souselements16');
        $devisd->souselements17 = $request->get('souselements17');
        $devisd->souselements18 = $request->get('souselements18');
        $devisd->souselements19 = $request->get('souselements19');
        $devisd->souselements20 = $request->get('souselements20');
        $devisd->souselements21 = $request->get('souselements21');
        $devisd->souselements22 = $request->get('souselements22');
        $devisd->souselements23 = $request->get('souselements23');
        $devisd->souselements24 = $request->get('souselements24');
        $devisd->souselements25 = $request->get('souselements25');
        $devisd->souselements26 = $request->get('souselements26');
        $devisd->souselements27 = $request->get('souselements27');
        $devisd->souselements28 = $request->get('souselements28');
        $devisd->souselements29 = $request->get('souselements29');
        $devisd->souselements30 = $request->get('souselements30');
        $devisd->souselements31 = $request->get('souselements31');
        $devisd->souselements32 = $request->get('souselements32');
        $devisd->souselements33 = $request->get('souselements33');
        $devisd->souselements34 = $request->get('souselements34');
        $devisd->souselements35 = $request->get('souselements35');
        $devisd->souselements36 = $request->get('souselements36');
        $devisd->souselements37 = $request->get('souselements37');
        $devisd->souselements38 = $request->get('souselements38');
        $devisd->souselements39 = $request->get('souselements39');
        $devisd->souselements40 = $request->get('souselements40');
        $devisd->souselements41 = $request->get('souselements41');
        $devisd->souselements42 = $request->get('souselements42');
        $devisd->souselements43 = $request->get('souselements43');
        $devisd->souselements44 = $request->get('souselements44');
        $devisd->souselements45 = $request->get('souselements45');
        $devisd->souselements46 = $request->get('souselements46');
        $devisd->souselements47 = $request->get('souselements47');
        $devisd->souselements48 = $request->get('souselements48');
        $devisd->souselements49 = $request->get('souselements49');
        $devisd->souselements50 = $request->get('souselements50');
        $devisd->souselements51 = $request->get('souselements51');
        $devisd->souselements52 = $request->get('souselements52');
        $devisd->souselements53 = $request->get('souselements53');
        $devisd->souselements54 = $request->get('souselements54');
        $devisd->souselements55 = $request->get('souselements55');
        $devisd->souselements56 = $request->get('souselements56');
        $devisd->souselements57 = $request->get('souselements57');
        $devisd->souselements58 = $request->get('souselements58');
        $devisd->souselements59 = $request->get('souselements59');
        $devisd->souselements60 = $request->get('souselements60');
        $devisd->souselements61 = $request->get('souselements61');
        $devisd->souselements62 = $request->get('souselements62');
        $devisd->souselements63 = $request->get('souselements63');
        $devisd->souselements64 = $request->get('souselements64');
        $devisd->souselements65 = $request->get('souselements65');
        $devisd->souselements66 = $request->get('souselements66');
        $devisd->souselements67 = $request->get('souselements67');
        $devisd->souselements68 = $request->get('souselements68');
        $devisd->souselements69 = $request->get('souselements69');
        $devisd->souselements70 = $request->get('souselements70');
        $devisd->souselements71 = $request->get('souselements71');
        $devisd->souselements72 = $request->get('souselements72');
        $devisd->souselements73 = $request->get('souselements73');
        $devisd->souselements74 = $request->get('souselements74');
        $devisd->souselements75 = $request->get('souselements75');
        $devisd->souselements76 = $request->get('souselements76');
        $devisd->souselements77 = $request->get('souselements77');
        $devisd->souselements78 = $request->get('souselements78');
        $devisd->souselements79 = $request->get('souselements79');
        $devisd->souselements80 = $request->get('souselements80');
        $devisd->souselements81 = $request->get('souselements81');
        $devisd->souselements82 = $request->get('souselements82');
        $devisd->souselements83 = $request->get('souselements83');
        $devisd->souselements84 = $request->get('souselements84');
        $devisd->souselements85 = $request->get('souselements85');
        $devisd->souselements86 = $request->get('souselements86');
        $devisd->souselements87 = $request->get('souselements87');
        $devisd->souselements88 = $request->get('souselements88');
        $devisd->souselements89 = $request->get('souselements89');
        $devisd->souselements90 = $request->get('souselements90');
        $devisd->souselements91 = $request->get('souselements91');
        $devisd->souselements92 = $request->get('souselements92');
        $devisd->souselements93 = $request->get('souselements93');
        $devisd->souselements94 = $request->get('souselements94');
        $devisd->souselements95 = $request->get('souselements95');
        $devisd->souselements96 = $request->get('souselements96');
        $devisd->souselements97 = $request->get('souselements97');
        $devisd->souselements98 = $request->get('souselements98');
        $devisd->souselements99 = $request->get('souselements99');
        $devisd->souselements100 = $request->get('souselements100');
        $devisd->souselements101 = $request->get('souselements101');
        $devisd->souselements102 = $request->get('souselements102');
        $devisd->souselements103 = $request->get('souselements103');
        $devisd->souselements104 = $request->get('souselements104');
        $devisd->souselements105 = $request->get('souselements105');
        $devisd->souselements106 = $request->get('souselements106');
        $devisd->souselements107 = $request->get('souselements107');
        $devisd->souselements108 = $request->get('souselements108');
        $devisd->souselements109 = $request->get('souselements109');
        $devisd->souselements110 = $request->get('souselements110');
        $devisd->souselements111 = $request->get('souselements111');
        $devisd->souselements112 = $request->get('souselements112');
        $devisd->souselements113 = $request->get('souselements113');
        $devisd->souselements114 = $request->get('souselements114');
        $devisd->souselements115 = $request->get('souselements115');
        $devisd->souselements116 = $request->get('souselements116');
        $devisd->souselements117 = $request->get('souselements117');
        $devisd->souselements118 = $request->get('souselements118');
        $devisd->souselements119 = $request->get('souselements119');
        $devisd->souselements120 = $request->get('souselements120');
        $devisd->souselements121 = $request->get('souselements121');
        $devisd->souselements122 = $request->get('souselements122');
        $devisd->souselements123 = $request->get('souselements123');
        $devisd->souselements124 = $request->get('souselements124');
        $devisd->souselements125 = $request->get('souselements125');
        $devisd->souselements126 = $request->get('souselements126');
        $devisd->souselements127 = $request->get('souselements127');
        $devisd->souselements128 = $request->get('souselements128');
        $devisd->souselements129 = $request->get('souselements129');
        $devisd->souselements130 = $request->get('souselements130');
        $devisd->souselements131 = $request->get('souselements131');
        $devisd->souselements132 = $request->get('souselements132');
        $devisd->souselements133 = $request->get('souselements133');
        $devisd->souselements134 = $request->get('souselements134');
        $devisd->souselements135 = $request->get('souselements135');
        $devisd->souselements136 = $request->get('souselements136');
        $devisd->souselements137 = $request->get('souselements137');
        $devisd->souselements138 = $request->get('souselements138');
        $devisd->souselements139 = $request->get('souselements139');
        $devisd->souselements140 = $request->get('souselements140');
        $devisd->souselements141 = $request->get('souselements141');
        $devisd->souselements142 = $request->get('souselements142');
        $devisd->souselements143 = $request->get('souselements143');
        $devisd->souselements144 = $request->get('souselements144');
        $devisd->souselements145 = $request->get('souselements145');
        $devisd->souselements146 = $request->get('souselements146');
        $devisd->souselements147 = $request->get('souselements147');
        $devisd->souselements148 = $request->get('souselements148');
        $devisd->souselements149 = $request->get('souselements149');
        $devisd->souselements150 = $request->get('souselements150');
       
        $devisd->prix1 = $request->get('prix1');
        $devisd->prix2 = $request->get('prix2');
        $devisd->prix3 = $request->get('prix3');
        $devisd->prix4 = $request->get('prix4');
        $devisd->prix5 = $request->get('prix5');
        $devisd->prix6 = $request->get('prix6');
        $devisd->prix7 = $request->get('prix7');
        $devisd->prix8 = $request->get('prix8');
        $devisd->prix9 = $request->get('prix9');
        $devisd->prix10 = $request->get('prix10');
        $devisd->prix11 = $request->get('prix11');
        $devisd->prix12 = $request->get('prix12');
        $devisd->prix13 = $request->get('prix13');
        $devisd->prix14 = $request->get('prix14');
        $devisd->prix15 = $request->get('prix15');
        $devisd->prix16 = $request->get('prix16');
        $devisd->prix17 = $request->get('prix17');
        $devisd->prix18 = $request->get('prix18');
        $devisd->prix19 = $request->get('prix19');
        $devisd->prix20 = $request->get('prix20');
        $devisd->prix21 = $request->get('prix21');
        $devisd->prix22 = $request->get('prix22');
        $devisd->prix23 = $request->get('prix23');
        $devisd->prix24 = $request->get('prix24');
        $devisd->prix25 = $request->get('prix25');
        $devisd->prix26 = $request->get('prix26');
        $devisd->prix27 = $request->get('prix27');
        $devisd->prix28 = $request->get('prix28');
        $devisd->prix29 = $request->get('prix29');
        $devisd->prix30 = $request->get('prix30');
        $devisd->prix31 = $request->get('prix31');
        $devisd->prix32 = $request->get('prix32');
        $devisd->prix33 = $request->get('prix33');
        $devisd->prix34 = $request->get('prix34');
        $devisd->prix35 = $request->get('prix35');
        $devisd->prix36 = $request->get('prix36');
        $devisd->prix37 = $request->get('prix37');
        $devisd->prix38 = $request->get('prix38');
        $devisd->prix39 = $request->get('prix39');
        $devisd->prix40 = $request->get('prix40');
        $devisd->prix41 = $request->get('prix41');
        $devisd->prix42 = $request->get('prix42');
        $devisd->prix43 = $request->get('prix43');
        $devisd->prix44 = $request->get('prix44');
        $devisd->prix45 = $request->get('prix45');
        $devisd->prix46 = $request->get('prix46');
        $devisd->prix47 = $request->get('prix47');
        $devisd->prix48 = $request->get('prix48');
        $devisd->prix49 = $request->get('prix49');
        $devisd->prix50 = $request->get('prix50');
        $devisd->prix51 = $request->get('prix51');
        $devisd->prix52 = $request->get('prix52');
        $devisd->prix53 = $request->get('prix53');
        $devisd->prix54 = $request->get('prix54');
        $devisd->prix55 = $request->get('prix55');
        $devisd->prix56 = $request->get('prix56');
        $devisd->prix57 = $request->get('prix57');
        $devisd->prix58 = $request->get('prix58');
        $devisd->prix59 = $request->get('prix59');
        $devisd->prix60 = $request->get('prix60');
        $devisd->prix61 = $request->get('prix61');
        $devisd->prix62 = $request->get('prix62');
        $devisd->prix63 = $request->get('prix63');
        $devisd->prix64 = $request->get('prix64');
        $devisd->prix65 = $request->get('prix65');
        $devisd->prix66 = $request->get('prix66');
        $devisd->prix67 = $request->get('prix67');
        $devisd->prix68 = $request->get('prix68');
        $devisd->prix69 = $request->get('prix69');
        $devisd->prix70 = $request->get('prix70');
        $devisd->prix71 = $request->get('prix71');
        $devisd->prix72 = $request->get('prix72');
        $devisd->prix73 = $request->get('prix73');
        $devisd->prix74 = $request->get('prix74');
        $devisd->prix75 = $request->get('prix75');
        $devisd->prix76 = $request->get('prix76');
        $devisd->prix77 = $request->get('prix77');
        $devisd->prix78 = $request->get('prix78');
        $devisd->prix79 = $request->get('prix79');
        $devisd->prix80 = $request->get('prix80');
        $devisd->prix81 = $request->get('prix81');
        $devisd->prix82 = $request->get('prix82');
        $devisd->prix83 = $request->get('prix83');
        $devisd->prix84 = $request->get('prix84');
        $devisd->prix85 = $request->get('prix85');
        $devisd->prix86 = $request->get('prix86');
        $devisd->prix87 = $request->get('prix87');
        $devisd->prix88 = $request->get('prix88');
        $devisd->prix89 = $request->get('prix89');
        $devisd->prix90 = $request->get('prix90');
        $devisd->prix91 = $request->get('prix91');
        $devisd->prix92 = $request->get('prix92');
        $devisd->prix93 = $request->get('prix93');
        $devisd->prix94 = $request->get('prix94');
        $devisd->prix95 = $request->get('prix95');
        $devisd->prix96 = $request->get('prix96');
        $devisd->prix97 = $request->get('prix97');
        $devisd->prix98 = $request->get('prix98');
        $devisd->prix99 = $request->get('prix99');
        $devisd->prix100 = $request->get('prix100');
        $devisd->prix101 = $request->get('prix101');
        $devisd->prix102 = $request->get('prix102');
        $devisd->prix103 = $request->get('prix103');
        $devisd->prix104 = $request->get('prix104');
        $devisd->prix105 = $request->get('prix105');
        $devisd->prix106 = $request->get('prix106');
        $devisd->prix107 = $request->get('prix107');
        $devisd->prix108 = $request->get('prix108');
        $devisd->prix109 = $request->get('prix109');
        $devisd->prix110 = $request->get('prix110');
        $devisd->prix111 = $request->get('prix111');
        $devisd->prix112 = $request->get('prix112');
        $devisd->prix113 = $request->get('prix113');
        $devisd->prix114 = $request->get('prix114');
        $devisd->prix115 = $request->get('prix115');
        $devisd->prix116 = $request->get('prix116');
        $devisd->prix117 = $request->get('prix117');
        $devisd->prix118 = $request->get('prix118');
        $devisd->prix119 = $request->get('prix119');
        $devisd->prix120 = $request->get('prix120');
        $devisd->prix121 = $request->get('prix121');
        $devisd->prix122 = $request->get('prix122');
        $devisd->prix123 = $request->get('prix123');
        $devisd->prix124 = $request->get('prix124');
        $devisd->prix125 = $request->get('prix125');
        $devisd->prix126 = $request->get('prix126');
        $devisd->prix127 = $request->get('prix127');
        $devisd->prix128 = $request->get('prix128');
        $devisd->prix129 = $request->get('prix129');
        $devisd->prix130 = $request->get('prix130');
        $devisd->prix131 = $request->get('prix131');
        $devisd->prix132 = $request->get('prix132');
        $devisd->prix133 = $request->get('prix133');
        $devisd->prix134 = $request->get('prix134');
        $devisd->prix135 = $request->get('prix135');
        $devisd->prix136 = $request->get('prix136');
        $devisd->prix137 = $request->get('prix137');
        $devisd->prix138 = $request->get('prix138');
        $devisd->prix139 = $request->get('prix139');
        $devisd->prix140 = $request->get('prix140');
        $devisd->prix141 = $request->get('prix141');
        $devisd->prix142 = $request->get('prix142');
        $devisd->prix143 = $request->get('prix143');
        $devisd->prix144 = $request->get('prix144');
        $devisd->prix145 = $request->get('prix145');
        $devisd->prix146 = $request->get('prix146');
        $devisd->prix147 = $request->get('prix147');
        $devisd->prix148 = $request->get('prix148');
        $devisd->prix149 = $request->get('prix149');
        $devisd->prix150 = $request->get('prix150');

        $devisd->elements11 = $request->get('elements11');
        $devisd->elements12 = $request->get('elements12');
        $devisd->elements13 = $request->get('elements13');
        $devisd->elements14 = $request->get('elements14');
        $devisd->elements15 = $request->get('elements15');
        $devisd->devis_id = $request->devis_id;
        $devisd->patient_id = $request->patient_id;
        $devisd->user_id = Auth::id();
         $devisd->save();

        return redirect()->route('devis.index')->with('success', 'ajouté avec succès !');
    }

    public function export_devisd($id)
    {

        $this->authorize('create', Patient::class);
        $devis = Devisd::find($id);

        $pdf = \PDF::loadView('admin.etats.devisd', compact('devisd'));

        $pdf->save(storage_path('devisd').'.pdf');

        return $pdf->stream('devisd.pdf');
    }

    public function create()
    {
       
        $devis = Devis::all();
        return view('admin.devisd.create', compact('devis'));
    }
}
